-- Seed data for the "articles" table. Idempotent (ON CONFLICT DO NOTHING) -- safe to re-run.
INSERT INTO articles (title, slug, excerpt, category, author, author_role, author_bio, date, reading_time, cover_image, featured, content, tags, sort_order) VALUES
('Pourquoi le TypeScript est devenu indispensable en 2024', 'typescript-indispensable-2024', 'Le typage statique transforme la façon dont nous écrivons du JavaScript. Découvrez pourquoi TypeScript est désormais un standard de l''industrie.', 'Développement Web', 'Konan A.', 'Lead Developer', 'Lead Developer chez ALAK DIGITAL, passionné par la qualité du code et l''architecture logicielle.', '2024-08-15', '6 min', 'https://images.pexels.com/photos/11035471/pexels-photo-11035471.jpeg?auto=compress&cs=tinysrgb&h=650&w=940', true, '<p>Le typage statique transforme la façon dont nous écrivons du JavaScript. En ajoutant une couche de sécurité au moment du développement, TypeScript permet de détecter les erreurs avant même que le code ne soit exécuté.</p><h2>Pourquoi adopter TypeScript ?</h2><p>L''un des bénéfices majeurs est la <strong>lisibilité du code</strong>. En explicitant les types, on documente directement le code, ce qui facilite la collaboration et la maintenance.</p><blockquote>TypeScript s''intègre parfaitement avec les outils modernes : Vite, ESLint, Prettier. L''écosystème a mûri au point que le coût d''adoption est minimal comparé aux bénéfices.</blockquote><h3>Les avantages concrets</h3><ul><li>Détection des erreurs à la compilation, avant l''exécution</li><li>Autocomplétion intelligente dans l''éditeur</li><li>Refactoring sécurisé et fiable</li><li>Documentation vivante grâce aux types</li></ul><p>Chez ALAK DIGITAL, tous nos projets web sont développés en <strong>TypeScript strict</strong>. C''est un investissement sur la qualité long terme.</p>', ARRAY['TypeScript', 'JavaScript', 'Web', 'Qualité'], 0)
ON CONFLICT (slug) DO NOTHING;

INSERT INTO articles (title, slug, excerpt, category, author, author_role, author_bio, date, reading_time, cover_image, featured, content, tags, sort_order) VALUES
('Transformer une PME africaine: le rôle du digital', 'transformation-digitale-pme-africaine', 'La transformation digitale n''est plus une option pour les PME africaines. Comment les technologies web et mobile redéfinissent la compétitivité.', 'Transformation digitale', 'Kouamé B.', 'Digital Strategist', 'Stratégiste digital, accompagne les entreprises dans leur transformation digitale.', '2024-07-20', '8 min', 'https://images.pexels.com/photos/3184292/pexels-photo-3184292.jpeg?auto=compress&cs=tinysrgb&h=650&w=940', false, '<p>La transformation digitale n''est plus une option pour les PME africaines. L''adoption d''outils numériques est devenue un facteur clé de compétitivité.</p><h2>Un levier de croissance</h2><p>Les entreprises qui digitalisent leurs processus internes gagnent en efficacité, réduisent leurs coûts opérationnels et améliorent l''expérience de leurs clients.</p><blockquote>Le mobile joue un rôle central en Afrique. Avec un taux de pénétration smartphone en croissance constante, les applications mobiles sont souvent le premier point de contact entre une entreprise et ses clients.</blockquote>', ARRAY['Transformation digitale', 'Afrique', 'PME', 'Mobile'], 1)
ON CONFLICT (slug) DO NOTHING;

INSERT INTO articles (title, slug, excerpt, category, author, author_role, author_bio, date, reading_time, cover_image, featured, content, tags, sort_order) VALUES
('Docker et CI/CD: automatiser vos déploiements', 'docker-cicd-automatiser-deploiements', 'La conteneurisation et l''intégration continue sont au cœur du DevOps moderne. Guide pratique pour mettre en place un pipeline efficace.', 'DevOps', 'Traoré M.', 'DevOps Engineer', 'Ingénieur DevOps, spécialiste de l''automatisation et des infrastructures cloud.', '2024-06-10', '10 min', 'https://images.pexels.com/photos/7376/startup-photos.jpg?auto=compress&cs=tinysrgb&h=650&w=940', false, '<p>La conteneurisation avec Docker a révolutionné la façon dont nous déployons les applications. En encapsulant l''application et ses dépendances dans un conteneur, on garantit une cohérence entre les environnements de développement et de production.</p><h2>Qu''est-ce que la CI/CD ?</h2><p>La <strong>CI/CD</strong> (Continuous Integration / Continuous Deployment) automatise le processus de livraison.</p>', ARRAY['Docker', 'CI/CD', 'DevOps', 'GitHub Actions'], 2)
ON CONFLICT (slug) DO NOTHING;

INSERT INTO articles (title, slug, excerpt, category, author, author_role, author_bio, date, reading_time, cover_image, featured, content, tags, sort_order) VALUES
('Concevoir un Design System qui évolue', 'concevoir-design-system', 'Un Design System n''est pas qu''une bibliothèque de composants. C''est un langage visuel partagé qui garantit la cohérence de vos produits.', 'UI/UX', 'Aya K.', 'UI/UX Designer', 'Designer produit, crée des interfaces cohérentes et accessibles.', '2024-05-05', '7 min', 'https://images.pexels.com/photos/1966447/pexels-photo-1966447.jpeg?auto=compress&cs=tinysrgb&h=650&w=940', false, '<p>Un Design System va au-delà d''une simple bibliothèque de composants. C''est un <strong>langage visuel partagé</strong> qui garantit la cohérence de vos produits digitaux.</p>', ARRAY['Design System', 'UI/UX', 'Figma', 'Cohérence'], 3)
ON CONFLICT (slug) DO NOTHING;

INSERT INTO articles (title, slug, excerpt, category, author, author_role, author_bio, date, reading_time, cover_image, featured, content, tags, sort_order) VALUES
('FastAPI vs Laravel: choisir son backend', 'fastapi-vs-laravel-backend', 'Python ou PHP ? Deux approches différentes pour construire des API performantes. Comparatif pour vous aider à choisir.', 'Backend', 'Konan A.', 'Lead Developer', 'Lead Developer chez ALAK DIGITAL, passionné par la qualité du code et l''architecture logicielle.', '2024-04-18', '9 min', 'https://images.pexels.com/photos/1181271/pexels-photo-1181271.jpeg?auto=compress&cs=tinysrgb&h=650&w=940', false, '<p>Le choix du framework backend dépend de nombreux facteurs : équipe, écosystème, performance, type de projet.</p>', ARRAY['FastAPI', 'Laravel', 'Python', 'PHP', 'Backend'], 4)
ON CONFLICT (slug) DO NOTHING;

INSERT INTO articles (title, slug, excerpt, category, author, author_role, author_bio, date, reading_time, cover_image, featured, content, tags, sort_order) VALUES
('Le SaaS en Afrique: opportunités et défis', 'saas-afrique-opportunites-defis', 'Le marché SaaS africain est en pleine croissance. Quelles opportunités pour les entrepreneurs et quels défis techniques à anticiper.', 'SaaS', 'Kouamé B.', 'Digital Strategist', 'Stratégiste digital, accompagne les entreprises dans leur transformation digitale.', '2024-03-22', '8 min', 'https://images.pexels.com/photos/3184465/pexels-photo-3184465.jpeg?auto=compress&cs=tinysrgb&h=650&w=940', false, '<p>Le marché SaaS africain connaît une croissance rapide, portée par la digitalisation des entreprises et l''augmentation de la connectivité internet.</p>', ARRAY['SaaS', 'Afrique', 'Entrepreneuriat', 'Cloud'], 5)
ON CONFLICT (slug) DO NOTHING;
