-- Seed data for the "projects" table. Idempotent (ON CONFLICT DO NOTHING) -- safe to re-run.
INSERT INTO projects (name, slug, sector, tagline, description, problem, solution, technologies, services, featured, year, client, duration, results, features, sort_order, image) VALUES
('EventFlow', 'eventflow', 'Événementiel', 'Plateforme de gestion d''événements et billetterie', 'EventFlow est une plateforme complète de gestion d''événements permettant aux organisateurs de créer, promouvoir et gérer leurs événements avec un système de billetterie intégré.', 'Les organisateurs d''événements en Côte d''Ivoire manquaient d''une solution locale pour gérer la billetterie, le check-in et l''analyse des événements en temps réel.', 'Nous avons conçu une plateforme web et mobile permettant la création d''événements, la vente de billets en ligne, le check-in QR code et le suivi analytique en temps réel.', ARRAY['React', 'FastAPI', 'PostgreSQL', 'Flutter', 'Redis', 'Docker'], ARRAY['Développement Web', 'Développement Mobile', 'Backend & API', 'DevOps & Cloud'], true, '2024', 'EventFlow CI', '5 mois', '[{"label":"Billets vendus","value":"50K+"},{"label":"Événements gérés","value":"200+"},{"label":"Temps de check-in","value":"-80%"}]', ARRAY['Billetterie en ligne avec paiement mobile', 'Check-in QR code via app mobile', 'Tableau de bord analytique en temps réel', 'Gestion multi-organisateurs', 'Notifications push automatiques'], 0, 'https://images.pexels.com/photos/11035471/pexels-photo-11035471.jpeg?auto=compress&cs=tinysrgb&h=650&w=940')
ON CONFLICT (slug) DO NOTHING;

INSERT INTO projects (name, slug, sector, tagline, description, problem, solution, technologies, services, featured, year, client, duration, results, features, sort_order, image) VALUES
('Garage Manager', 'garage-manager', 'SaaS Automotive', 'SaaS de gestion de garage automobile', 'Garage Manager est un logiciel SaaS permettant aux garagistes de gérer leurs réparations, stock de pièces, facturation et relation client depuis une interface unique.', 'Les garages automobiles géraient leurs opérations manuellement, avec des pertes de temps significatives et des erreurs de facturation fréquentes.', 'Un SaaS multi-tenant avec gestion des ordres de réparation, suivi du stock, facturation automatique et tableau de bord de performance.', ARRAY['React', 'Laravel', 'MySQL', 'Tailwind CSS', 'Docker'], ARRAY['Plateformes SaaS', 'Développement Web', 'Backend & API'], true, '2024', 'Garage Manager', '4 mois', '[{"label":"Garages actifs","value":"30+"},{"label":"Réparations/mois","value":"1.2K"},{"label":"Gain de temps","value":"60%"}]', ARRAY['Gestion des ordres de réparation', 'Suivi de stock de pièces détachées', 'Facturation automatique', 'Base de données clients', 'Tableau de bord de performance'], 1, 'https://images.pexels.com/photos/3184292/pexels-photo-3184292.jpeg?auto=compress&cs=tinysrgb&h=650&w=940')
ON CONFLICT (slug) DO NOTHING;

INSERT INTO projects (name, slug, sector, tagline, description, problem, solution, technologies, services, featured, year, client, duration, results, features, sort_order, image) VALUES
('Lavex', 'lavex', 'SaaS Services', 'Solution de gestion de pressing et blanchisserie', 'Lavex est une solution SaaS qui digitalise la gestion des pressings: prise en charge, suivi des commandes, notifications client et facturation.', 'Les pressings locaux ne disposaient d''aucun outil de suivi, entraînant des pertes de vêtements et une insatisfaction client.', 'Une plateforme web avec application mobile client permettant le suivi en temps réel des commandes et la notification par SMS.', ARRAY['React', 'FastAPI', 'PostgreSQL', 'Flutter'], ARRAY['Plateformes SaaS', 'Développement Mobile', 'Backend & API'], true, '2023', 'Lavex', '3 mois', '[{"label":"Pressings équipés","value":"15+"},{"label":"Commandes/mois","value":"800"},{"label":"Satisfaction client","value":"95%"}]', ARRAY['Prise en charge et étiquetage QR', 'Suivi des commandes en temps réel', 'Notifications SMS automatiques', 'Application mobile client', 'Facturation et statistiques'], 2, 'https://images.pexels.com/photos/7376/startup-photos.jpg?auto=compress&cs=tinysrgb&h=650&w=940')
ON CONFLICT (slug) DO NOTHING;

INSERT INTO projects (name, slug, sector, tagline, description, problem, solution, technologies, services, featured, year, client, duration, results, features, sort_order, image) VALUES
('VoucherConnect', 'voucherconnect', 'Fintech', 'Solution voucher et gestion de distribution', 'VoucherConnect est une plateforme permettant l''émission, la distribution et le suivi de vouchers numériques pour les programmes d''assistance sociale et commerciale.', 'Les organisations distribuant des vouchers manquaient d''un système sécurisé et traçable pour gérer l''émission et l''utilisation des vouchers.', 'Une plateforme sécurisée avec émission de vouchers uniques, validation par QR code et tableau de bord de suivi en temps réel.', ARRAY['React', 'FastAPI', 'PostgreSQL', 'Redis', 'Docker'], ARRAY['Plateformes SaaS', 'Développement Web', 'Backend & API', 'DevOps & Cloud'], false, '2023', 'VoucherConnect', '6 mois', '[{"label":"Vouchers émis","value":"100K+"},{"label":"Taux d''utilisation","value":"92%"},{"label":"Transactions sécurisées","value":"100%"}]', ARRAY['Émission de vouchers uniques', 'Validation par QR code', 'Tableau de bord de distribution', 'Suivi en temps réel', 'Intégration paiement mobile'], 3, 'https://images.pexels.com/photos/1966447/pexels-photo-1966447.jpeg?auto=compress&cs=tinysrgb&h=650&w=940')
ON CONFLICT (slug) DO NOTHING;

INSERT INTO projects (name, slug, sector, tagline, description, problem, solution, technologies, services, featured, year, client, duration, results, features, sort_order, image) VALUES
('ModaStock', 'modastock', 'Logistique', 'Gestion de stock et d''inventaire cloud', 'ModaStock est une solution cloud de gestion de stock permettant aux entreprises de suivre leurs inventaires en temps réel, gérer leurs fournisseurs et automatiser leurs commandes.', 'Les PME géraient leurs stocks sur Excel, avec des écarts d''inventaire réguliers et aucune visibilité en temps réel.', 'Une plateforme web responsive avec application mobile de scan, alertes automatiques et rapports analytiques.', ARRAY['React', 'Laravel', 'MySQL', 'Flutter'], ARRAY['Plateformes SaaS', 'Développement Web', 'Développement Mobile'], false, '2024', 'ModaStock', '4 mois', '[{"label":"Articles gérés","value":"500K+"},{"label":"Précision inventaire","value":"99.5%"},{"label":"Temps de saisie","value":"-70%"}]', ARRAY['Gestion multi-entrepôts', 'Scan de codes-barres via mobile', 'Alertes de rupture de stock', 'Gestion des fournisseurs', 'Rapports analytiques avancés'], 4, 'https://images.pexels.com/photos/1181271/pexels-photo-1181271.jpeg?auto=compress&cs=tinysrgb&h=650&w=940')
ON CONFLICT (slug) DO NOTHING;

INSERT INTO projects (name, slug, sector, tagline, description, problem, solution, technologies, services, featured, year, client, duration, results, features, sort_order, image) VALUES
('CorpWeb Institution', 'corpweb-institution', 'Institutionnel', 'Plateforme institutionnelle et corporate', 'CorpWeb Institution est une plateforme web institutionnelle conçue pour une organisation internationale, intégrant gestion de contenu, publications et espace membre.', 'L''institution avait besoin d''une plateforme moderne pour communiquer, publier ses rapports et gérer ses membres avec un niveau de sécurité élevé.', 'Une plateforme sur mesure avec CMS intégré, espace membre sécurisé, gestion documentaire et multilingue.', ARRAY['React', 'FastAPI', 'PostgreSQL', 'Nginx', 'Docker'], ARRAY['Développement Web', 'Backend & API', 'DevOps & Cloud', 'UI/UX Design'], false, '2024', 'Organisation Internationale', '7 mois', '[{"label":"Membres actifs","value":"5K+"},{"label":"Documents publiés","value":"1.2K"},{"label":"Disponibilité","value":"99.9%"}]', ARRAY['CMS sur mesure multilingue', 'Espace membre sécurisé', 'Gestion documentaire', 'Publication de rapports', 'Authentification à deux facteurs'], 5, 'https://images.pexels.com/photos/3184465/pexels-photo-3184465.jpeg?auto=compress&cs=tinysrgb&h=650&w=940')
ON CONFLICT (slug) DO NOTHING;
